"use client";

import { Plus, Trash2 } from "lucide-react";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

import { SaveIndicator } from "@/src/components/save-indicator";
import { StageStepper } from "@/src/components/stage-stepper";
import { useAutoSave } from "@/src/hooks/use-auto-save";

type Scene = { id: string; order: number; title: string; timeOfDay: string; durationEst: number; visualDescription: string; actions: string[]; dialogues: Array<{ speaker: string; line: string }>; narration: string; emotionalGoal: string; shots: unknown[] };
type Episode = { id: string; title: string; targetDuration: number; scenes: Scene[] };

async function api(url: string, init?: RequestInit) { const response = await fetch(url, init); const result = response.status === 204 ? null : await response.json(); if (!response.ok) throw new Error(result?.error?.message ?? "请求失败"); return result; }

export function ScriptEditor({ projectId, initialEpisode }: { projectId: string; initialEpisode: Episode }) {
  const [scenes, setScenes] = useState(initialEpisode.scenes);
  const [selectedId, setSelectedId] = useState(initialEpisode.scenes[0]?.id ?? "");
  const [message, setMessage] = useState("");
  const selected = scenes.find((scene) => scene.id === selectedId) ?? null;
  const save = useAutoSave(selected, async (scene) => { if (!scene) return; const body: Partial<Scene> = { ...scene }; delete body.id; delete body.shots; await api(`/api/scenes/${scene.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); }, Boolean(selected));

  useEffect(() => { void api(`/api/projects/${projectId}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ lastStage: "script" }) }); }, [projectId]);
  const totals = useMemo(() => ({ duration: scenes.reduce((sum, scene) => sum + scene.durationEst, 0), dialogue: Math.round(scenes.reduce((sum, scene) => sum + scene.dialogues.reduce((words, line) => words + line.line.length, 0), 0) / 4), shots: scenes.reduce((sum, scene) => sum + scene.shots.length, 0) }), [scenes]);

  async function addScene(formData: FormData) { try { const scene = await api(`/api/episodes/${initialEpisode.id}/scenes`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ title: formData.get("title"), timeOfDay: formData.get("timeOfDay"), durationEst: Number(formData.get("durationEst")), visualDescription: "", actions: [], dialogues: [], narration: "", emotionalGoal: "" }) }); setScenes((items) => [...items, { ...scene, shots: [] }]); setSelectedId(scene.id); } catch (error) { setMessage(error instanceof Error ? error.message : "创建失败"); } }
  async function removeScene(scene: Scene) { try { await api(`/api/scenes/${scene.id}`, { method: "DELETE" }); const next = scenes.filter((item) => item.id !== scene.id).map((item,index) => ({...item, order:index+1})); setScenes(next); setSelectedId(next[0]?.id ?? ""); } catch (error) { setMessage(error instanceof Error ? error.message : "删除失败"); } }
  async function splitSelected() { if (!selected || selected.durationEst < 2) return; const title = window.prompt("拆分后新场景标题", `${selected.title}（下半场）`); if (!title) return; try { const firstDuration = Math.floor(selected.durationEst / 2); const created = await api(`/api/scenes/${selected.id}/split`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ title, durationEst: firstDuration }) }); const next = scenes.map((item)=>item.id===selected.id?{...item,durationEst:firstDuration}:item); next.splice(selected.order,0,{...created,shots:[]}); setScenes(next.map((item,index)=>({...item,order:index+1}))); } catch (error) { setMessage(error instanceof Error ? error.message : "拆分失败"); } }
  async function mergeNext() { if (!selected) return; try { const updated = await api(`/api/scenes/${selected.id}/merge-next`, { method: "POST" }); const next = scenes.filter((item)=>item.order!==selected.order+1).map((item)=>item.id===selected.id?{...item,...updated}:item).map((item,index)=>({...item,order:index+1})); setScenes(next); } catch (error) { setMessage(error instanceof Error ? error.message : "合并失败"); } }
  function patch(patchValue: Partial<Scene>) { if (!selected) return; setScenes((items) => items.map((scene) => scene.id === selected.id ? { ...scene, ...patchValue } : scene)); }

  return <>
    <StageStepper active="script" episodeId={initialEpisode.id} projectId={projectId} />
    <div className="page-head"><div><h1 className="page-title">{initialEpisode.title} · 单集剧本</h1><p className="page-copy">把一集拆成可独立转为镜头的结构化场景。</p></div><div className="inline-actions"><SaveIndicator retry={save.retry} state={save.state} /><button className="button secondary" disabled={!selected || selected.durationEst < 2} onClick={()=>void splitSelected()}>拆分当前场景</button><button className="button secondary" disabled={!selected || selected.order===scenes.length} onClick={()=>void mergeNext()}>合并下一场</button><Link className="button" href={`/projects/${projectId}/episodes/${initialEpisode.id}/shots`}>下一步：分镜编辑</Link></div></div>
    {message && <div className="warning" style={{ marginBottom: 14 }}>{message}</div>}
    <div className="script-layout">
      <aside className="card scene-nav"><strong>场景列表</strong>{scenes.map((scene) => <button className={`scene-item ${scene.id === selectedId ? "active" : ""}`} key={scene.id} onClick={() => setSelectedId(scene.id)}><strong>SC {String(scene.order).padStart(2,"0")} · {scene.title}</strong><span>{scene.durationEst}s · {scene.shots.length} 镜头</span></button>)}<form action={addScene} style={{ borderTop: "1px solid var(--line)", marginTop: 10, paddingTop: 12 }}><div className="field"><input className="input" name="title" placeholder="新场景标题" required /></div><div className="bible-grid"><input className="input" name="timeOfDay" placeholder="时间" /><input className="input" defaultValue="15" name="durationEst" type="number" /></div><button className="button small" style={{ marginTop: 9 }}><Plus size={12} /> 新增场景</button></form></aside>
      <section className="card script-paper">{selected ? <><div className="inline-actions" style={{ justifyContent: "space-between" }}><div className="scene-heading">SC {String(selected.order).padStart(2,"0")} · {selected.title}</div><button className="button danger small" onClick={() => void removeScene(selected)}><Trash2 size={12} /> 删除</button></div><div className="bible-grid"><div className="field"><label>场景标题</label><input className="input" value={selected.title} onChange={(event) => patch({ title: event.target.value })} /></div><div className="field"><label>时间</label><input className="input" value={selected.timeOfDay} onChange={(event) => patch({ timeOfDay: event.target.value })} /></div></div><div className="field"><label>预计时长（秒）</label><input className="input" min="0" type="number" value={selected.durationEst} onChange={(event) => patch({ durationEst: Number(event.target.value) })} /></div><div className="field"><label>画面描述</label><textarea className="textarea" value={selected.visualDescription} onChange={(event) => patch({ visualDescription: event.target.value })} /></div><div className="field"><label>人物动作（每行一条）</label><textarea className="textarea" value={selected.actions.join("\n")} onChange={(event) => patch({ actions: event.target.value.split("\n").filter(Boolean) })} /></div><div className="field"><label>对白（格式：角色：台词）</label><textarea className="textarea" value={selected.dialogues.map((line) => `${line.speaker}：${line.line}`).join("\n")} onChange={(event) => patch({ dialogues: event.target.value.split("\n").filter(Boolean).map((line) => { const [speaker,...content] = line.split(/[：:]/); return { speaker, line: content.join("：") }; }) })} /></div><div className="field"><label>旁白</label><textarea className="textarea" value={selected.narration} onChange={(event) => patch({ narration: event.target.value })} /></div><div className="field"><label>情绪目标</label><textarea className="textarea" value={selected.emotionalGoal} onChange={(event) => patch({ emotionalGoal: event.target.value })} /></div></> : <div className="empty"><strong>请选择或创建一个场景</strong></div>}</section>
      <aside className="card metrics-panel"><h3 style={{ marginTop: 0 }}>时长估算</h3><div className="metric-grid"><div className="metric"><strong>{initialEpisode.targetDuration}s</strong><span>目标时长</span></div><div className="metric"><strong>{totals.duration}s</strong><span>预计总时长</span></div><div className="metric"><strong>{totals.dialogue}s</strong><span>对白估算</span></div><div className="metric"><strong>{totals.shots || Math.ceil(totals.duration / 5)}</strong><span>建议/已有镜头</span></div></div>{totals.duration > initialEpisode.targetDuration * 1.15 && <div className="warning" style={{ marginTop: 12 }}>预计时长明显超过目标，建议压缩对白或场景。</div>}</aside>
    </div>
  </>;
}
