"use client";

import { ArrowDown, ArrowUp, Plus, Trash2 } from "lucide-react";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

import { SaveIndicator } from "@/src/components/save-indicator";
import { StageStepper } from "@/src/components/stage-stepper";
import { useAutoSave } from "@/src/hooks/use-auto-save";

type ShotFields = { characters: string[]; location: string; shotSize: "ecu"|"cu"|"ms"|"ws"|"ews"; angle: string; cameraMovement: string; action: string; expression: string; lighting: string; styleNote: string; dialogueOrNarration: string; continuityFromPrev: string; continuityToNext: string; exclude: string[] };
type Shot = { id: string; order: number; sceneId: string; durationEst: number; fields: ShotFields; scene: { id: string; order: number; title: string } };
type Scene = { id: string; order: number; title: string };
type Episode = { id: string; title: string; targetDuration: number; scenes: Scene[] };
const defaults: ShotFields = { characters: [], location: "", shotSize: "ms", angle: "平视", cameraMovement: "固定镜头", action: "", expression: "", lighting: "", styleNote: "", dialogueOrNarration: "", continuityFromPrev: "", continuityToNext: "", exclude: [] };
async function api(url: string, init?: RequestInit) { const response = await fetch(url, init); const result = response.status === 204 ? null : await response.json(); if (!response.ok) throw new Error(result?.error?.message ?? "请求失败"); return result; }

export function ShotsEditor({ projectId, episode, initialShots }: { projectId: string; episode: Episode; initialShots: Shot[] }) {
  const [shots, setShots] = useState(initialShots);
  const [selectedId, setSelectedId] = useState(initialShots[0]?.id ?? "");
  const [message, setMessage] = useState("");
  const selected = shots.find((shot) => shot.id === selectedId) ?? null;
  const save = useAutoSave(selected, async (shot) => { if (!shot) return; await api(`/api/shots/${shot.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ sceneId: shot.sceneId, durationEst: shot.durationEst, fields: shot.fields }) }); }, Boolean(selected));
  useEffect(() => { void api(`/api/projects/${projectId}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ lastStage: "shots" }) }); }, [projectId]);
  const total = useMemo(() => shots.reduce((sum, shot) => sum + shot.durationEst, 0), [shots]);
  const warnings = [shots.length > 0 && (shots.length < 8 || shots.length > 15) ? `当前 ${shots.length} 个镜头，建议保持在 8–15 个。` : "", total > episode.targetDuration * 1.15 ? "镜头总时长明显超过单集目标。" : ""].filter(Boolean);

  async function addShot() { try { const scene = episode.scenes[0]; if (!scene) throw new Error("请先在剧本页创建场景"); const shot = await api(`/api/episodes/${episode.id}/shots`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ sceneId: scene.id, durationEst: 4, fields: defaults }) }); const complete = { ...shot, scene }; setShots((items) => [...items, complete]); setSelectedId(shot.id); } catch (error) { setMessage(error instanceof Error ? error.message : "创建失败"); } }
  async function move(shot: Shot, order: number) { if (order < 1 || order > shots.length) return; await api(`/api/shots/${shot.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ order }) }); const items = shots.filter((item) => item.id !== shot.id); items.splice(order - 1,0,shot); setShots(items.map((item,index)=>({...item,order:index+1}))); }
  async function remove(shot: Shot) { await api(`/api/shots/${shot.id}`, { method: "DELETE" }); const next = shots.filter((item)=>item.id!==shot.id).map((item,index)=>({...item,order:index+1})); setShots(next); setSelectedId(next[0]?.id ?? ""); }
  async function splitSelected() { if (!selected || selected.durationEst < 2) return; try { const firstDuration = Math.floor(selected.durationEst/2); const created = await api(`/api/shots/${selected.id}/split`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ durationEst: firstDuration }) }); const next = shots.map((item)=>item.id===selected.id?{...item,durationEst:firstDuration}:item); next.splice(selected.order,0,{...created,scene:selected.scene,fields:selected.fields}); setShots(next.map((item,index)=>({...item,order:index+1}))); } catch (error) { setMessage(error instanceof Error ? error.message : "拆分失败"); } }
  async function mergeNext() { if (!selected) return; try { const updated = await api(`/api/shots/${selected.id}/merge-next`, { method: "POST" }); const next = shots.filter((item)=>item.order!==selected.order+1).map((item)=>item.id===selected.id?{...item,...updated}:item).map((item,index)=>({...item,order:index+1})); setShots(next); } catch (error) { setMessage(error instanceof Error ? error.message : "合并失败"); } }
  function patch(value: Partial<Shot>) { if (!selected) return; setShots((items)=>items.map((shot)=>shot.id===selected.id?{...shot,...value}:shot)); }
  function patchFields(value: Partial<ShotFields>) { if (selected) patch({ fields: { ...selected.fields, ...value } }); }

  return <>
    <StageStepper active="shots" episodeId={episode.id} projectId={projectId} />
    <div className="page-head"><div><h1 className="page-title">{episode.title} · 分镜编辑</h1><p className="page-copy">人工建立 8–15 个连续镜头，顺序变化后自动重编号。</p></div><div className="inline-actions"><SaveIndicator retry={save.retry} state={save.state} /><button className="button secondary" onClick={() => void addShot()}><Plus size={14} /> 新增镜头</button><button className="button secondary" disabled={!selected || selected.durationEst < 2} onClick={()=>void splitSelected()}>拆分当前镜头</button><button className="button secondary" disabled={!selected || selected.order===shots.length} onClick={()=>void mergeNext()}>合并下一镜</button><Link className="button" href={`/projects/${projectId}/episodes/${episode.id}/production`}>下一步：生产工作台</Link></div></div>
    {message && <div className="warning" style={{ marginBottom: 14 }}>{message}</div>}
    {warnings.map((warning)=><div className="warning" style={{ marginBottom: 10 }} key={warning}>{warning}</div>)}
    <div className="shots-layout">
      <div className="shot-list">{shots.map((shot)=><article className={`card shot-card ${shot.id===selectedId?"active":""}`} key={shot.id} onClick={()=>setSelectedId(shot.id)}><div className="shot-num"><strong>{String(shot.order).padStart(2,"0")}</strong><span>{shot.durationEst}s</span></div><div><span className="tag">SC {String(shot.scene.order).padStart(2,"0")} · {shot.fields.shotSize.toUpperCase()}</span><h3 style={{margin:"7px 0 4px"}}>{shot.fields.action || "待填写动作"}</h3><p className="page-copy">{shot.fields.location || shot.scene.title} · {shot.fields.cameraMovement} · {shot.fields.expression || "表情待定"}</p></div><div className="inline-actions"><button className="button secondary small" disabled={shot.order===1} onClick={(event)=>{event.stopPropagation();void move(shot,shot.order-1)}}><ArrowUp size={12}/></button><button className="button secondary small" disabled={shot.order===shots.length} onClick={(event)=>{event.stopPropagation();void move(shot,shot.order+1)}}><ArrowDown size={12}/></button></div></article>)}{shots.length===0&&<div className="card empty"><strong>还没有镜头</strong>点击“新增镜头”开始人工分镜。</div>}</div>
      <aside className="card shot-details">{selected?<><div className="inline-actions" style={{justifyContent:"space-between"}}><h3>SHOT {String(selected.order).padStart(2,"0")}</h3><button className="button danger small" onClick={()=>void remove(selected)}><Trash2 size={12}/></button></div><div className="bible-grid"><div className="field"><label>所属场景</label><select className="select" value={selected.sceneId} onChange={(event)=>patch({sceneId:event.target.value,scene:episode.scenes.find((scene)=>scene.id===event.target.value)??selected.scene})}>{episode.scenes.map((scene)=><option value={scene.id} key={scene.id}>SC {scene.order} · {scene.title}</option>)}</select></div><div className="field"><label>时长</label><input className="input" min="1" max="30" type="number" value={selected.durationEst} onChange={(event)=>patch({durationEst:Number(event.target.value)})}/></div><div className="field"><label>景别</label><select className="select" value={selected.fields.shotSize} onChange={(event)=>patchFields({shotSize:event.target.value as ShotFields["shotSize"]})}><option value="ecu">大特写</option><option value="cu">特写</option><option value="ms">中景</option><option value="ws">全景</option><option value="ews">大远景</option></select></div><div className="field"><label>角度</label><input className="input" value={selected.fields.angle} onChange={(event)=>patchFields({angle:event.target.value})}/></div></div>{([ ["location","地点与环境"], ["cameraMovement","运镜"], ["action","人物动作"], ["expression","表情"], ["lighting","光线"], ["styleNote","风格备注"], ["dialogueOrNarration","对白/旁白/音效"], ["continuityFromPrev","承接上一镜"], ["continuityToNext","衔接下一镜"] ] as const).map(([field,label])=><div className="field" key={field}><label>{label}</label><textarea className="textarea" value={selected.fields[field]} onChange={(event)=>patchFields({[field]:event.target.value})}/></div>)}<div className="field"><label>排除内容（每行一条）</label><textarea className="textarea" value={selected.fields.exclude.join("\n")} onChange={(event)=>patchFields({exclude:event.target.value.split("\n").filter(Boolean)})}/></div></>:<div className="empty">选择一个镜头进行编辑</div>}</aside>
    </div>
    <div className="card card-pad" style={{marginTop:14}}><div className="meta"><strong>镜头总数 {shots.length}</strong><strong>总时长 {total}s / 目标 {episode.targetDuration}s</strong></div><div className="progress"><i style={{width:`${Math.min(100,(total/episode.targetDuration)*100)}%`}}/></div></div>
  </>;
}
